Allow specifying image magick versions through env

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,78 +1,84 @@
 #!/bin/bash
+# bin/compile BUILD_DIR CACHE_DIR ENV_DIR
+
+set -e            # fail fast
+set -o nounset    # fail on unset variables
 
 indent() {
   sed -u 's/^/       /'
 }
 
-echo "-----> Install ImageMagick"
+header() {
+  echo "-----> $*"
+}
 
-BUILD_DIR=$1
-CACHE_DIR=$2
+header "Install ImageMagick"
+
+BUILD_DIR=${1:-}
+CACHE_DIR=${2:-}
+ENV_DIR=${3:-}
+
 VENDOR_DIR="$BUILD_DIR/vendor"
 INSTALL_DIR="$VENDOR_DIR/imagemagick"
-CACHE_FILE="$CACHE_DIR/imagemagick.tar.gz"
 
+IMAGEMAGICK_VERSION="$(test -f $ENV_DIR/IMAGEMAGICK_VERSION && cat $ENV_DIR/IMAGEMAGICK_VERSION)"
+IMAGEMAGICK_VERSION=${IMAGEMAGICK_VERSION:-6.9.3-10}
 
-if [ ! -f $CACHE_FILE ]; then
-  # install imagemagick
-  IMAGE_MAGICK_VERSION="${IMAGE_MAGICK_VERSION:-6.9.3-9}"
-  IMAGE_MAGICK_FILE="ImageMagick-$IMAGE_MAGICK_VERSION.tar.gz"
-  IMAGE_MAGICK_DIR="ImageMagick-$IMAGE_MAGICK_VERSION"
+IMAGEMAGICK_CACHED_BUILD="$CACHE_DIR/imagemagick.tar.gz"
+
+echo $IMAGEMAGICK_VERSION
+
+if [ "$IMAGEMAGICK_VERSION" != "$(cat "$CACHE_DIR/IMAGEMAGICK_VERSION")" ]; then
+  echo "New version detected"
+  echo $IMAGEMAGICK_VERSION > "$CACHE_DIR/IMAGEMAGICK_VERSION"
+  rm -f "$IMAGEMAGICK_CACHED_BUILD"
+fi
+
+if [ -f "$IMAGEMAGICK_CACHED_BUILD" ]; then
+  header "Extracting ImageMagick $CACHE_FILE => $VENDOR_DIR"
+  tar xzf $CACHE_FILE -C $VENDOR_DIR
+else
+  IMAGEMAGICK_FILE="ImageMagick-$IMAGEMAGICK_VERSION.tar.gz"
+  IMAGEMAGICK_DIR="ImageMagick-$IMAGEMAGICK_VERSION"
   # SSL cert used on imagemagick not recognized by heroku.
-  IMAGE_MAGICK_URL="http://www.imagemagick.org/download/releases/$IMAGE_MAGICK_FILE"
+  IMAGEMAGICK_URL="http://www.imagemagick.org/download/releases/$IMAGEMAGICK_FILE"
 
-  echo "-----> Downloading ImageMagick from $IMAGE_MAGICK_URL"
-  wget $IMAGE_MAGICK_URL -P $BUILD_DIR | indent
-  
-  echo "-----> Extracting ImageMagick from $BUILD_DIR/$IMAGE_MAGICK_FILE"
-  if [ ! -f $BUILD_DIR/$IMAGE_MAGICK_FILE ]; then
-    echo "Error: Unable to download ImageMagick" | indent
+  header "Downloading ImageMagick from $IMAGEMAGICK_URL"
+  wget $IMAGEMAGICK_URL -P $BUILD_DIR | indent
+
+  header "Extracting ImageMagick from $BUILD_DIR/$IMAGEMAGICK_FILE"
+  if [ ! -f $BUILD_DIR/$IMAGEMAGICK_FILE ]; then
+    echo "Error: Unable to download image magick" | indent
     ls $BUILD_DIR | indent
     exit 1;
   fi
-  tar xvf $BUILD_DIR/$IMAGE_MAGICK_FILE | indent
+  tar xvf $BUILD_DIR/$IMAGEMAGICK_FILE | indent
 
-  echo "-----> Building ImageMagick"
-  cd $IMAGE_MAGICK_DIR
+  header "Building ImageMagick"
+  cd $IMAGEMAGICK_DIR
   export CPPFLAGS="-I$INSTALL_DIR/include"
   export LDFLAGS="-L$INSTALL_DIR/lib"
   ./configure --prefix=$INSTALL_DIR
   make && make install
   cd ..
-  rm -rf $IMAGE_MAGICK_DIR
+  rm -rf $IMAGEMAGICK_DIR
 
-  # cache for future deploys
-  echo "-----> Caching ImageMagick installation"
+  header "Caching ImageMagick installation"
   cd $VENDOR_DIR
   REL_INSTALL_DIR="imagemagick"
   tar czf $REL_INSTALL_DIR.tar.gz $REL_INSTALL_DIR
-  mv $REL_INSTALL_DIR.tar.gz $CACHE_FILE
-
-else
-  # cache exists, extract it
-  echo "-----> Extracting ImageMagick $CACHE_FILE => $VENDOR_DIR"
-  tar xzf $CACHE_FILE -C $VENDOR_DIR
+  mv $REL_INSTALL_DIR.tar.gz $IMAGEMAGICK_CACHED_BUILD
 fi
 
-# update PATH and LD_LIBRARY_PATH
-echo "-----> Updating environment variables"
+header "Updating environment variables"
 PROFILE_PATH="$BUILD_DIR/.profile.d/imagemagick.sh"
 ACTUAL_INSTALL_PATH="$HOME/vendor/imagemagick"
 mkdir -p $(dirname $PROFILE_PATH)
 echo "export PATH=$ACTUAL_INSTALL_PATH/bin:\$PATH" >> $PROFILE_PATH
 echo "export LD_LIBRARY_PATH=$ACTUAL_INSTALL_PATH/lib:\$LD_LIBRARY_PATH" >> $PROFILE_PATH
 
-# DOWNLOAD_URL="http://www.imagemagick.org/download/ImageMagick-6.9.2-0.tar.gz"
+header "Updating configuration file"
+mkdir $BUILD_DIR/.magick
+cp -rf $VENDOR_DIR/imagemagick/etc/ImageMagick-*/* $BUILD_DIR/.magick/
 
-# echo "DOWNLOAD_URL = " $DOWNLOAD_URL | indent
-
-# cd $BUILD_DIR
-# mkdir -p $VENDOR_DIR
-# cd $VENDOR_DIR
-# curl -L --silent $DOWNLOAD_URL | tar xz
-
-# echo "exporting PATH and LIBRARY_PATH" | indent
-# PROFILE_PATH="$BUILD_DIR/.profile.d/imagemagick.sh"
-# mkdir -p $(dirname $PROFILE_PATH)
-# echo 'export PATH="$PATH:$HOME/vendor/ImageMagick-6.9.2/bin"' >> $PROFILE_PATH
-# echo 'export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/vendor/ImageMagick-6.9.2/lib"' >> $PROFILE_PATH
+exit 0;
